"""Build the MathMD launcher icon from real font glyph outlines.

Design (owner-final): dark background, four clean white document text
lines (round caps, last one short), and the wordmark "MathD" below —
M and D in blue (MD = markdown embedded), ath white, geometric sans
(TeX Gyre Adventor Bold, single-storey 'a'). Single source for the
Android VectorDrawable and an SVG/PNG preview.

Run from repo root:
  uv run --with fonttools,cairosvg python tools/icon/build_icon.py
Fonts come from the sandbox TeX Live 2026 install.
"""

from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen

TEX = "/root/.local/texlive/2026/texmf-dist/fonts/opentype/public/tex-gyre"
PAGELLA_MATH = "/root/.local/texlive/2026/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf"
ADVENTOR_BOLD = f"{TEX}/texgyreadventor-bold.otf"  # geometric sans, single-storey 'a'

OUT_VECTOR = "app/src/main/res/drawable/ic_launcher_foreground.xml"
OUT_SVG = "docs/icon-preview.svg"
OUT_PNG = "docs/icon-preview.png"

# ---- palette (Wikipedia-style: dark bg, pure white lines, blue accent) ----
BG = "#1C1B1F"          # adaptive-icon background layer
LINE = "#FFFFFF"
BLUE = "#4FA3FF"


def glyph_path(font, ch):
    """Return (svg_path_data, advance_width, (xMin, yMin, xMax, yMax))."""
    gs = font.getGlyphSet()
    name = font.getBestCmap()[ord(ch)]
    g = gs[name]
    pen = SVGPathPen(gs)
    g.draw(pen)
    bp = BoundsPen(gs)
    g.draw(bp)
    return pen.getCommands(), g.width, bp.bounds


def glyph_group(d, fill, tx, ty, s):
    return (
        f'<g transform="translate({tx:.3f} {ty:.3f}) scale({s:.6f} {-s:.6f})">'
        f'<path fill="{fill}" d="{d}"/></g>'
    )


def main():
    sans = TTFont(ADVENTOR_BOLD)

    # Line geometry: content box 28..80 on both axes — equal 28dp margins on
    # all four sides of the 108dp canvas (safe from the rounded-corner mask).
    X0, X1 = 28.0, 80.0
    ROWS = (28.0, 38.0, 48.0, 58.0)

    # ---- wordmark "MathD": M and D blue (MD = markdown embedded), ath white ----
    colors = {"M": BLUE, "a": LINE, "t": LINE, "h": LINE, "D": BLUE}
    word = [glyph_path(sans, c) for c in "MathD"]
    cap = max(b[3] for _, _, b in word)
    word_scale = 12.0 / cap
    advances = [w for _, w, _ in word]
    total_w = sum(advances) * word_scale
    x = (108.0 - total_w) / 2.0
    baseline = 80.0
    word_parts = []
    for (d, w, _b), ch in zip(word, "MathD"):
        word_parts.append(glyph_group(d, colors[ch], x, baseline, word_scale))
        x += w * word_scale

    # ---- clean white text lines (round caps), no decorations ----
    def hline(y, x0, x1):
        return (f'<path stroke="{LINE}" stroke-width="2.6" stroke-linecap="round" '
                f'd="M{x0} {y}h{x1 - x0}"/>')

    parts = [
        hline(ROWS[0], X0, X1),   # full
        hline(ROWS[1], X0, X1),   # full
        hline(ROWS[2], X0, X1),   # full
        hline(ROWS[3], X0, 60.0), # short
        *word_parts,
    ]

    def svg_path_to_android(tag: str) -> str:
        # SVG: <path fill="#x" stroke="#y" stroke-width="1.2" stroke-linecap="round" d="..."/>
        # Android vector path attrs differ; rebuild attribute-by-attribute.
        import re
        d = re.search(r'd="([^"]*)"', tag).group(1)
        fill = re.search(r'fill="([^"]*)"', tag)
        stroke = re.search(r'stroke="([^"]*)"', tag)
        sw = re.search(r'stroke-width="([^"]*)"', tag)
        attrs = [f'android:pathData="{d}"']
        if fill:
            attrs.insert(0, f'android:fillColor="{fill.group(1)}"')
        if stroke:
            attrs.insert(0, f'android:strokeColor="{stroke.group(1)}"')
        if sw:
            attrs.append(f'android:strokeWidth="{sw.group(1)}"')
        if 'stroke-linecap="round"' in tag:
            attrs.append('android:strokeLineCap="round"')
        return "    <path " + " ".join(attrs) + " />\n"

    vector = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!--\n'
        '  Generated by tools/icon/build_icon.py from Noto Sans Bold and\n'
        '  TeX Gyre Pagella Math glyph outlines (GUST Font License / OFL;\n'
        '  embedding outlines in an icon is fine).\n'
        '  Design: white document lines with embedded integral/summation\n'
        '  symbols, and the "MathD" wordmark (M,D red = markdown embedded).\n'
        '  Re-run the script to regenerate; do not hand-edit.\n'
        '-->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
    )
    for p in parts:
        if p.startswith("<g transform="):
            # glyph group: convert transform to Android group attrs + inner path
            import re
            tr = re.search(r'transform="([^"]*)"', p).group(1)
            m = re.match(r"translate\(([-\d.]+) ([-\d.]+)\) scale\(([-\d.]+) ([-\d.]+)\)", tr)
            tx, ty, sx, sy = (float(v) for v in m.groups())
            d = re.search(r'd="([^"]*)"', p).group(1)
            fill = re.search(r'fill="([^"]*)"', p).group(1)
            vector += (
                f'    <group android:scaleX="{sx}" android:scaleY="{sy}"\n'
                f'        android:translateX="{tx}" android:translateY="{ty}">\n'
                f'        <path android:fillColor="{fill}" android:pathData="{d}" />\n'
                f'    </group>\n'
            )
        else:
            vector += svg_path_to_android(p)
    vector += "</vector>\n"

    with open(OUT_VECTOR, "w") as f:
        f.write(vector)

    # ---- SVG preview (with dark background) ----
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="432" height="432" '
        f'viewBox="0 0 108 108">'
        f'<rect width="108" height="108" rx="20" fill="{BG}"/>'
        + "".join(parts)
        + "</svg>"
    )
    with open(OUT_SVG, "w") as f:
        f.write(svg)

    try:
        import cairosvg
        cairosvg.svg2png(bytestring=svg.encode(), write_to=OUT_PNG, output_width=432, output_height=432)
        print(f"PNG preview: {OUT_PNG}")
    except ImportError:
        print("cairosvg not available; SVG preview written only")

    print(f"VectorDrawable: {OUT_VECTOR}")
    print(f"SVG preview:    {OUT_SVG}")
    print(f"word width: {total_w:.1f}dp, x0={(108-total_w)/2:.1f}, cap={cap} upm, scale={word_scale:.5f}")


if __name__ == "__main__":
    main()
